# Generated by Django 5.1.15 on 2026-10-07 22:32

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=media.models.media_upload_path),
        ),
    ]
