# Generated by Django 5.1.15 on 2026-10-10 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_album_mediafile_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='media.album'),
        ),
    ]
